server:
  port: 8081

# nohup java -jar -Dspring.profiles.active=prod myworkspace-0.0.1-SNAPSHOT.jar &

spring:
  profiles:
    active: default
  servlet:
  #multipart 파일처리 조건
    multipart:      max-file-size: -1      max-request-size: -1
  #database 접속 정보
  datasource:
         #jdbc:mysql://엔드포인트/데이터베이스?옵션...    url: jdbc:mysql://myworkspace.ciip0izfdfsn.ap-northeast-2.rds.amazonaws.com/myworkspace?useUnicode=true&characterEncoding=utf-8
    username: admin
    password: password123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:    show-sql: true # 데이터처리할 대 SQL문을 보여줌
    generate-ddl: true # 클래스 정의에 따른 테이블 및 데이터베이스 객체 생성     
  redis:
    host: 127.0.0.1
    port: 6379        
api:
  base-path: http://localhost:8080

---
spring:
  profiles: prod
  redis:
    host: 13.125.207.0
    port: 6379  
  
api:
  base-path: http://ec2-15-164-212-136.ap-northeast-2.compute.amazonaws.com:8080
  
          
